# This is a basic workflow to help you get started with Actions

name: Synch to Hugging Face Hib

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        env:
        HF: ${{secrets.HF}}
      run: git remote add space Https://frustea:$HF@huggingface.co/spaces/frustea/summarization
      - name: Push to hub
      env:
      HF: ${{secrets.HF}}
      run: git push force https://frustea:$HF@huggingface.co/spaces/frustea/summarization
      
      




